[theme]
primaryColor = "#3b82f6"
backgroundColor = "#0F1116"
secondaryBackgroundColor = "#1A1D23"
textColor = "#ececec"
font = "sans serif"

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false
